LVGL_VERSION = v9.2.0
LVGL_SITE = https://github.com/lvgl/lvgl.git
LVGL_SITE_METHOD = git
LVGL_LICENSE = MIT
LVGL_LICENSE_FILES = LICENSE.txt
LVGL_INSTALL_STAGING = YES
LVGL_SUPPORTS_IN_SOURCE_BUILD = NO

LVGL_CONF_OPTS += -DLV_BUILD_TEST=OFF -DLV_BUILD_EXAMPLES=OFF

$(eval $(cmake-package))

